package spannerdef

import (
	"fmt"
	"github.com/cloudspannerecosystem/memefish/ast"
	"github.com/cloudspannerecosystem/memefish/token"
	"reflect"
	"sort"
	"strings"
)

// Creation and ADD COLUMN preserve generation semantics. Altering an existing
// generated/identity column needs a dedicated migration plan, not ALTER TYPE.
func validateGenerationChanges(current, desired *Schema) error {
	for name, next := range desired.Tables {
		prev, ok := current.Tables[name]
		if !ok {
			continue
		}
		for colName, col := range next.Columns {
			old, ok := prev.Columns[colName]
			if !ok {
				continue
			}
			if !sameGeneration(old, col) || old.Hidden != col.Hidden ||
				((old.Generation != "" || col.Generation != "") && (old.Type != col.Type || old.NotNull != col.NotNull || old.Default != col.Default)) {
				return fmt.Errorf("unsupported generation or visibility change for column %s.%s; apply it explicitly before updating the desired schema", name, colName)
			}
		}
	}
	return nil
}

func canonicalIdentity(identity *ast.IdentityColumn) string {
	params := make([]string, 0, len(identity.Params)+1)
	hasKind := false
	for _, param := range identity.Params {
		params = append(params, param.SQL())
		if _, ok := param.(*ast.BitReversedPositive); ok {
			hasKind = true
		}
	}
	// Match the normalization used for AUTO_INCREMENT and bare IDENTITY.
	if !hasKind {
		params = append(params, "BIT_REVERSED_POSITIVE")
	}
	sort.Strings(params)
	return "GENERATED BY DEFAULT AS IDENTITY (" + strings.Join(params, " ") + ")"
}

// setColumnAdditionOrder resolves expression references after every column has
// been declared. CREATE TABLE permits forward references; separate ADD COLUMN
// statements must instead introduce each dependency first.
func setColumnAdditionOrder(table *Table, expressions map[*Column]ast.Expr, names map[string]*Column) error {
	columns := make([]*Column, 0, len(table.Columns))
	for _, column := range table.Columns {
		columns = append(columns, column)
	}
	sort.Slice(columns, func(i, j int) bool {
		if columns[i].Order != columns[j].Order {
			return columns[i].Order < columns[j].Order
		}
		return columns[i].Name < columns[j].Name
	})
	dependencies := make(map[*Column][]*Column)
	for column, expr := range expressions {
		dependencies[column] = referencedColumns(expr, names)
	}
	state := make(map[*Column]int)
	ordered := make([]*Column, 0, len(columns))
	var visit func(*Column) error
	visit = func(column *Column) error {
		switch state[column] {
		case 1:
			return fmt.Errorf("cyclic generated column dependency on %s.%s", table.Name, column.Name)
		case 2:
			return nil
		}
		state[column] = 1
		for _, dependency := range dependencies[column] {
			if err := visit(dependency); err != nil {
				return err
			}
		}
		state[column] = 2
		ordered = append(ordered, column)
		return nil
	}
	for _, column := range columns {
		if err := visit(column); err != nil {
			return err
		}
	}
	for i, column := range ordered {
		column.additionOrder = i
	}
	return nil
}

func referencedColumns(expr ast.Expr, names map[string]*Column) []*Column {
	var columns []*Column
	visitColumnReferences(expr, names, func(ident *ast.Ident) {
		columns = append(columns, names[strings.ToLower(ident.Name)])
	})
	return columns
}

// Identifiers also occur as field names, function names, aliases and date parts.
// Only references to declared columns are dependencies.
func visitColumnReferences(expr ast.Expr, names map[string]*Column, visit func(*ast.Ident)) {
	ignored := make(map[ast.Node]bool)
	add := func(ident *ast.Ident) {
		if names[strings.ToLower(ident.Name)] != nil {
			visit(ident)
		}
	}
	ast.Inspect(expr, func(node ast.Node) bool {
		if ignored[node] {
			return false
		}
		switch node := node.(type) {
		case *ast.CallExpr:
			ignored[node.Func] = true
			if index := datePartArgument(node); index >= 0 && index < len(node.Args) {
				ignored[node.Args[index]] = true
			}
		case *ast.NamedArg:
			ignored[node.Name] = true
		case *ast.BracedConstructorField:
			ignored[node.Name] = true
		case *ast.ExtractExpr:
			ignored[node.Part] = true
		case *ast.SelectorExpr:
			ignored[node.Ident] = true
		case *ast.ReplaceFieldsArg:
			ignored[node.Field] = true
		case ast.Type, *ast.AsAlias, *ast.SequenceArg, *ast.ModelArg, *ast.TableArg:
			return false
		case *ast.WithExpr:
			scope := make(map[string]*Column, len(names))
			for name, column := range names {
				scope[name] = column
			}
			for _, binding := range node.Vars {
				visitColumnReferences(binding.Expr, scope, visit)
				delete(scope, strings.ToLower(binding.Name.Name))
			}
			visitColumnReferences(node.Expr, scope, visit)
			return false
		case *ast.LambdaArg:
			scope := make(map[string]*Column, len(names))
			for name, column := range names {
				scope[name] = column
			}
			for _, arg := range node.Args {
				delete(scope, strings.ToLower(arg.Name))
			}
			visitColumnReferences(node.Expr, scope, visit)
			return false
		case *ast.Path:
			add(node.Idents[0])
			return false
		case *ast.Ident:
			add(node)
		}
		return true
	})
}

// The parser models these grammar arguments as ordinary expressions, but they
// denote units (including WEEK(MONDAY)), never column references.
func datePartArgument(call *ast.CallExpr) int {
	path := call.Func.Idents
	if len(path) == 2 && strings.EqualFold(path[0].Name, "SAFE") {
		path = path[1:]
	}
	if len(path) != 1 {
		return -1
	}
	switch strings.ToUpper(path[0].Name) {
	case "DATE_DIFF", "DATETIME_DIFF", "TIMESTAMP_DIFF", "TIME_DIFF":
		return 2
	case "DATE_TRUNC", "DATETIME_TRUNC", "TIMESTAMP_TRUNC", "TIME_TRUNC", "LAST_DAY":
		return 1
	default:
		return -1
	}
}

func normalizeGenerationExpression(expr ast.Expr, names map[string]*Column) {
	visitColumnReferences(expr, names, func(ident *ast.Ident) { ident.Name = strings.ToLower(ident.Name) })
	ast.Inspect(expr, func(node ast.Node) bool {
		if call, ok := node.(*ast.CallExpr); ok {
			path := call.Func.Idents
			if len(path) == 1 || (len(path) == 2 && strings.EqualFold(path[0].Name, "SAFE")) {
				for _, name := range path {
					name.Name = strings.ToUpper(name.Name)
				}
			}
		}
		return true
	})
}

func sameGeneration(a, b *Column) bool {
	if a.Generation == b.Generation {
		return true
	}
	if a.generationExpr == nil || b.generationExpr == nil {
		return false
	}
	return equalGenerationAST(reflect.ValueOf(a.generationExpr), reflect.ValueOf(b.generationExpr))
}

// Compare expression structure, not serialized SQL: redundant parentheses and
// source offsets do not change it, while operator grouping and literal/field
// spelling do. Retain token presence because optional tokens such as STORED
// carry semantics even though their source offsets do not.
func equalGenerationAST(a, b reflect.Value) bool {
	unwrap := func(v reflect.Value) reflect.Value {
		for v.IsValid() {
			if v.Kind() == reflect.Interface && !v.IsNil() {
				v = v.Elem()
				continue
			}
			if paren, ok := v.Interface().(*ast.ParenExpr); ok && paren != nil {
				v = reflect.ValueOf(paren.Expr)
				continue
			}
			break
		}
		return v
	}
	a, b = unwrap(a), unwrap(b)
	if !a.IsValid() || !b.IsValid() {
		return a.IsValid() == b.IsValid()
	}
	if a.Type() != b.Type() {
		return false
	}
	if pos, ok := a.Interface().(token.Pos); ok {
		return pos.Invalid() == b.Interface().(token.Pos).Invalid()
	}
	switch a.Kind() {
	case reflect.Pointer, reflect.Interface:
		if a.IsNil() || b.IsNil() {
			return a.IsNil() == b.IsNil()
		}
		return equalGenerationAST(a.Elem(), b.Elem())
	case reflect.Struct:
		for i := 0; i < a.NumField(); i++ {
			if !equalGenerationAST(a.Field(i), b.Field(i)) {
				return false
			}
		}
		return true
	case reflect.Slice:
		if a.Len() != b.Len() {
			return false
		}
		for i := 0; i < a.Len(); i++ {
			if !equalGenerationAST(a.Index(i), b.Index(i)) {
				return false
			}
		}
		return true
	default:
		return reflect.DeepEqual(a.Interface(), b.Interface())
	}
}
