package spannerdef

import (
	"github.com/stretchr/testify/require"
	"testing"
)

func TestOmniColumnGeneration(t *testing.T) {
	t.Parallel()
	db := recreateDatabase(t, getTestConfig(t))
	desired := `CREATE TABLE T (Id INT64 NOT NULL GENERATED BY DEFAULT AS IDENTITY (BIT_REVERSED_POSITIVE), N INT64, G INT64 AS (N + 1) STORED, H INT64 HIDDEN) PRIMARY KEY(Id); CREATE TABLE A (Id INT64 NOT NULL AUTO_INCREMENT) PRIMARY KEY(Id);`
	require.NotEmpty(t, applySchema(t, db, desired, false))
	require.Empty(t, applySchema(t, db, desired, false))
}
