package spannerdef

import (
	"github.com/stretchr/testify/require"
	"testing"
)

func TestOmniColumnGeneration(t *testing.T) {
	t.Parallel()
	db := recreateDatabase(t, getTestConfig(t))
	desired := `CREATE TABLE T (Id INT64 NOT NULL GENERATED BY DEFAULT AS IDENTITY (BIT_REVERSED_POSITIVE), N INT64, G INT64 AS (N + 1) STORED, H INT64 HIDDEN) PRIMARY KEY(Id); CREATE TABLE A (Id INT64 NOT NULL AUTO_INCREMENT) PRIMARY KEY(Id);`
	require.NotEmpty(t, applySchema(t, db, desired, false))
	require.Empty(t, applySchema(t, db, desired, false))
}

func TestOmniIdentityParameterOrder(t *testing.T) {
	t.Parallel()
	db := recreateDatabase(t, getTestConfig(t))
	desired := "CREATE TABLE T (Id INT64 GENERATED BY DEFAULT AS IDENTITY (START COUNTER WITH 100 BIT_REVERSED_POSITIVE SKIP RANGE 1000, 2000)) PRIMARY KEY(Id)"
	require.NotEmpty(t, applySchema(t, db, desired, false))
	require.Empty(t, applySchema(t, db, desired, false))
}

func TestOmniGeneratedColumnForwardDependencies(t *testing.T) {
	t.Parallel()
	db := recreateDatabase(t, getTestConfig(t))
	current := "CREATE TABLE T (Id INT64 NOT NULL) PRIMARY KEY(Id)"
	desired := "CREATE TABLE T (Id INT64 NOT NULL, G INT64 AS (H + 1) STORED, H INT64 AS (N + 1) STORED, N INT64) PRIMARY KEY(Id)"
	require.NotEmpty(t, applySchema(t, db, current, false))
	require.Equal(t, []string{"ALTER TABLE T ADD COLUMN N INT64", "ALTER TABLE T ADD COLUMN H INT64 AS (N + 1) STORED", "ALTER TABLE T ADD COLUMN G INT64 AS (H + 1) STORED"}, applySchema(t, db, desired, false))
	require.Empty(t, applySchema(t, db, desired, false))
}
