package spannerdef

import (
	"fmt"
	"github.com/cloudspannerecosystem/memefish/ast"
	"sort"
	"strings"
)

// Creation and ADD COLUMN preserve generation semantics. Altering an existing
// generated/identity column needs a dedicated migration plan, not ALTER TYPE.
func validateGenerationChanges(current, desired *Schema) error {
	for name, next := range desired.Tables {
		prev, ok := current.Tables[name]
		if !ok {
			continue
		}
		for colName, col := range next.Columns {
			old, ok := prev.Columns[colName]
			if !ok {
				continue
			}
			if old.Generation != col.Generation || old.Hidden != col.Hidden ||
				((old.Generation != "" || col.Generation != "") && (old.Type != col.Type || old.NotNull != col.NotNull || old.Default != col.Default)) {
				return fmt.Errorf("unsupported generation or visibility change for column %s.%s; apply it explicitly before updating the desired schema", name, colName)
			}
		}
	}
	return nil
}

func canonicalIdentity(identity *ast.IdentityColumn) string {
	params := make([]string, 0, len(identity.Params)+1)
	hasKind := false
	for _, param := range identity.Params {
		params = append(params, param.SQL())
		if _, ok := param.(*ast.BitReversedPositive); ok {
			hasKind = true
		}
	}
	// Match the normalization used for AUTO_INCREMENT and bare IDENTITY.
	if !hasKind {
		params = append(params, "BIT_REVERSED_POSITIVE")
	}
	sort.Strings(params)
	return "GENERATED BY DEFAULT AS IDENTITY (" + strings.Join(params, " ") + ")"
}

// setColumnAdditionOrder resolves expression references after every column has
// been declared. CREATE TABLE permits forward references; separate ADD COLUMN
// statements must instead introduce each dependency first.
func setColumnAdditionOrder(table *Table, expressions map[*Column]ast.Expr, names map[string]*Column) error {
	columns := make([]*Column, 0, len(table.Columns))
	for _, column := range table.Columns {
		columns = append(columns, column)
	}
	sort.Slice(columns, func(i, j int) bool {
		if columns[i].Order != columns[j].Order {
			return columns[i].Order < columns[j].Order
		}
		return columns[i].Name < columns[j].Name
	})
	dependencies := make(map[*Column][]*Column)
	for column, expr := range expressions {
		dependencies[column] = referencedColumns(expr, names)
	}
	state := make(map[*Column]int)
	ordered := make([]*Column, 0, len(columns))
	var visit func(*Column) error
	visit = func(column *Column) error {
		switch state[column] {
		case 1:
			return fmt.Errorf("cyclic generated column dependency on %s.%s", table.Name, column.Name)
		case 2:
			return nil
		}
		state[column] = 1
		for _, dependency := range dependencies[column] {
			if err := visit(dependency); err != nil {
				return err
			}
		}
		state[column] = 2
		ordered = append(ordered, column)
		return nil
	}
	for _, column := range columns {
		if err := visit(column); err != nil {
			return err
		}
	}
	for i, column := range ordered {
		column.additionOrder = i
	}
	return nil
}

func referencedColumns(expr ast.Expr, names map[string]*Column) []*Column {
	var columns []*Column
	ignored := make(map[ast.Node]bool)
	add := func(name string) {
		if column := names[strings.ToLower(name)]; column != nil {
			columns = append(columns, column)
		}
	}
	ast.Inspect(expr, func(node ast.Node) bool {
		if ignored[node] {
			return false
		}
		switch node := node.(type) {
		case *ast.CallExpr:
			ignored[node.Func] = true // Function names are not column references.
		case *ast.NamedArg:
			ignored[node.Name] = true
		case *ast.Path:
			add(node.Idents[0].Name) // A field access depends on its root column.
			return false
		case *ast.Ident:
			add(node.Name)
		}
		return true
	})
	return columns
}
