package spannerdef

import (
	"github.com/stretchr/testify/require"
	"strings"
	"testing"
)

func TestColumnGenerationRoundTrip(t *testing.T) {
	for _, def := range []string{
		"N INT64 AS (Id + 1) STORED",
		"N INT64 AS (Id + 1) HIDDEN",
		"N INT64 GENERATED BY DEFAULT AS IDENTITY (BIT_REVERSED_POSITIVE)",
		"N INT64 AUTO_INCREMENT",
		"N INT64 HIDDEN",
	} {
		t.Run(def, func(t *testing.T) {
			desired := "CREATE TABLE T (Id INT64 NOT NULL, " + def + ") PRIMARY KEY (Id)"
			ddls, err := GenerateIdempotentDDLs(desired, "", GeneratorConfig{})
			require.NoError(t, err)
			require.Len(t, ddls, 1)
			normalized := strings.ReplaceAll(def, "AUTO_INCREMENT", "GENERATED BY DEFAULT AS IDENTITY (BIT_REVERSED_POSITIVE)")
			require.Contains(t, ddls[0], normalized)
			diff, err := GenerateIdempotentDDLs(desired, ddls[0], GeneratorConfig{})
			require.NoError(t, err)
			require.Empty(t, diff)
			added, err := GenerateIdempotentDDLs(desired, "CREATE TABLE T (Id INT64 NOT NULL) PRIMARY KEY (Id)", GeneratorConfig{})
			require.NoError(t, err)
			require.Equal(t, []string{"ALTER TABLE T ADD COLUMN " + normalized}, added)
		})
	}
}

func TestColumnGenerationChangesAreNotIgnored(t *testing.T) {
	base := "CREATE TABLE T (Id INT64 NOT NULL, N INT64 AS (Id + 1) STORED) PRIMARY KEY (Id)"
	for _, desired := range []string{
		strings.Replace(base, "Id + 1", "Id + 2", 1),
		strings.Replace(base, " AS (Id + 1) STORED", "", 1),
		strings.Replace(base, "STORED", "STORED HIDDEN", 1),
		strings.Replace(base, "N INT64", "N FLOAT64", 1),
	} {
		ddls, err := GenerateIdempotentDDLs(desired, base, GeneratorConfig{})
		require.ErrorContains(t, err, "unsupported generation or visibility change")
		require.Empty(t, ddls)
	}
}

func TestGeneratedColumnAdditionsPreserveDependencyOrder(t *testing.T) {
	current := "CREATE TABLE T (Id INT64 NOT NULL) PRIMARY KEY (Id)"
	desired := "CREATE TABLE T (Id INT64 NOT NULL, N INT64, G INT64 AS (N + 1) STORED) PRIMARY KEY (Id)"
	ddls, err := GenerateIdempotentDDLs(desired, current, GeneratorConfig{})
	require.NoError(t, err)
	require.Equal(t, []string{"ALTER TABLE T ADD COLUMN N INT64", "ALTER TABLE T ADD COLUMN G INT64 AS (N + 1) STORED"}, ddls)
}
