package spannerdef

import (
	"github.com/stretchr/testify/require"
	"strings"
	"testing"
)

func TestColumnGenerationRoundTrip(t *testing.T) {
	for _, def := range []string{
		"N INT64 AS (Id + 1) STORED",
		"N INT64 AS (Id + 1) HIDDEN",
		"N INT64 GENERATED BY DEFAULT AS IDENTITY (BIT_REVERSED_POSITIVE)",
		"N INT64 AUTO_INCREMENT",
		"N INT64 HIDDEN",
	} {
		t.Run(def, func(t *testing.T) {
			desired := "CREATE TABLE T (Id INT64 NOT NULL, " + def + ") PRIMARY KEY (Id)"
			ddls, err := GenerateIdempotentDDLs(desired, "", GeneratorConfig{})
			require.NoError(t, err)
			require.Len(t, ddls, 1)
			normalized := strings.ReplaceAll(def, "AUTO_INCREMENT", "GENERATED BY DEFAULT AS IDENTITY (BIT_REVERSED_POSITIVE)")
			require.Contains(t, ddls[0], normalized)
			diff, err := GenerateIdempotentDDLs(desired, ddls[0], GeneratorConfig{})
			require.NoError(t, err)
			require.Empty(t, diff)
			added, err := GenerateIdempotentDDLs(desired, "CREATE TABLE T (Id INT64 NOT NULL) PRIMARY KEY (Id)", GeneratorConfig{})
			require.NoError(t, err)
			require.Equal(t, []string{"ALTER TABLE T ADD COLUMN " + normalized}, added)
		})
	}
}

func TestColumnGenerationChangesAreNotIgnored(t *testing.T) {
	base := "CREATE TABLE T (Id INT64 NOT NULL, N INT64 AS (Id + 1) STORED) PRIMARY KEY (Id)"
	for _, desired := range []string{
		strings.Replace(base, "Id + 1", "Id + 2", 1),
		strings.Replace(base, " AS (Id + 1) STORED", "", 1),
		strings.Replace(base, "STORED", "STORED HIDDEN", 1),
		strings.Replace(base, "N INT64", "N FLOAT64", 1),
	} {
		ddls, err := GenerateIdempotentDDLs(desired, base, GeneratorConfig{})
		require.ErrorContains(t, err, "unsupported generation or visibility change")
		require.Empty(t, ddls)
	}
}

func TestGeneratedColumnAdditionsPreserveDependencyOrder(t *testing.T) {
	current := "CREATE TABLE T (Id INT64 NOT NULL) PRIMARY KEY (Id)"
	desired := "CREATE TABLE T (Id INT64 NOT NULL, N INT64, G INT64 AS (N + 1) STORED) PRIMARY KEY (Id)"
	ddls, err := GenerateIdempotentDDLs(desired, current, GeneratorConfig{})
	require.NoError(t, err)
	require.Equal(t, []string{"ALTER TABLE T ADD COLUMN N INT64", "ALTER TABLE T ADD COLUMN G INT64 AS (N + 1) STORED"}, ddls)
}

func TestIdentityParameterOrderIsEquivalent(t *testing.T) {
	canonical := "BIT_REVERSED_POSITIVE SKIP RANGE 1000, 2000 START COUNTER WITH 100"
	table := func(params string) string {
		return "CREATE TABLE T (Id INT64 GENERATED BY DEFAULT AS IDENTITY (" + params + ")) PRIMARY KEY(Id)"
	}
	for _, params := range []string{
		"START COUNTER WITH 100 BIT_REVERSED_POSITIVE SKIP RANGE 1000, 2000",
		"BIT_REVERSED_POSITIVE START COUNTER WITH 100 SKIP RANGE 1000, 2000",
		"SKIP RANGE 1000, 2000 START COUNTER WITH 100 BIT_REVERSED_POSITIVE",
		"START COUNTER WITH 100 SKIP RANGE 1000, 2000",
	} {
		ddls, err := GenerateIdempotentDDLs(table(params), table(canonical), GeneratorConfig{})
		require.NoError(t, err)
		require.Empty(t, ddls)
	}
	ddls, err := GenerateIdempotentDDLs(table(strings.Replace(canonical, "WITH 100", "WITH 200", 1)), table(canonical), GeneratorConfig{})
	require.ErrorContains(t, err, "unsupported generation or visibility change")
	require.Empty(t, ddls)
}

func TestGeneratedColumnForwardDependencies(t *testing.T) {
	current := "CREATE TABLE T (Id INT64 NOT NULL) PRIMARY KEY(Id)"
	for _, tc := range []struct {
		columns  string
		expected []string
	}{
		{"G INT64 AS (N + 1) STORED, N INT64", []string{"N INT64", "G INT64 AS (N + 1) STORED"}},
		{"G INT64 AS (H + 1) STORED, H INT64 AS (n + 1) STORED, N INT64", []string{"N INT64", "H INT64 AS (n + 1) STORED", "G INT64 AS (H + 1) STORED"}},
		{"ABS INT64 AS (ABS(N)) STORED, N INT64", []string{"N INT64", "ABS INT64 AS (ABS(N)) STORED"}},
		{"G STRING(MAX) AS (CONCAT('N', S)) STORED, S STRING(MAX), N INT64", []string{"S STRING(MAX)", `G STRING(MAX) AS (CONCAT("N", S)) STORED`, "N INT64"}},
	} {
		t.Run(tc.columns, func(t *testing.T) {
			desired := "CREATE TABLE T (Id INT64 NOT NULL, " + tc.columns + ") PRIMARY KEY(Id)"
			ddls, err := GenerateIdempotentDDLs(desired, current, GeneratorConfig{})
			require.NoError(t, err)
			expected := make([]string, len(tc.expected))
			for i, col := range tc.expected {
				expected[i] = "ALTER TABLE T ADD COLUMN " + col
			}
			require.Equal(t, expected, ddls)
		})
	}
	// A dependency already in the database does not need another ADD COLUMN.
	desired := "CREATE TABLE T (Id INT64 NOT NULL, G INT64 AS (Id + 1) STORED) PRIMARY KEY(Id)"
	ddls, err := GenerateIdempotentDDLs(desired, current, GeneratorConfig{})
	require.NoError(t, err)
	require.Equal(t, []string{"ALTER TABLE T ADD COLUMN G INT64 AS (Id + 1) STORED"}, ddls)
	// Reject cycles instead of recursing indefinitely or emitting a partial plan.
	ddls, err = GenerateIdempotentDDLs("CREATE TABLE T (Id INT64 NOT NULL, G INT64 AS (H + 1) STORED, H INT64 AS (G + 1) STORED) PRIMARY KEY(Id)", current, GeneratorConfig{})
	require.ErrorContains(t, err, "cyclic generated column dependency")
	require.Empty(t, ddls)
}

func TestGeneratedColumnsIgnoreNonReferenceIdentifiers(t *testing.T) {
	for _, columns := range []string{
		"D DATE, Year INT64 AS (EXTRACT(YEAR FROM D)) STORED",
		"D DATE, Day INT64 AS (DATE_DIFF(D, DATE '2020-01-01', DAY)) STORED",
		"D DATE, Month DATE AS (DATE_TRUNC(D, MONTH)) STORED",
		"J JSON, Foo JSON AS ((J).Foo) STORED",
		"N INT64 AS (WITH(N AS Id + 1, N + 1)) STORED",
		"N ARRAY<INT64> AS (ARRAY_TRANSFORM([Id], N -> N + 1)) STORED",
	} {
		t.Run(columns, func(t *testing.T) {
			current := "CREATE TABLE T (Id INT64 NOT NULL, " + columns + ") PRIMARY KEY(Id)"
			desired := strings.Replace(current, "Id INT64 NOT NULL,", "Id INT64 NOT NULL, Extra INT64,", 1)
			ddls, err := GenerateIdempotentDDLs(desired, current, GeneratorConfig{})
			require.NoError(t, err)
			require.Equal(t, []string{"ALTER TABLE T ADD COLUMN Extra INT64"}, ddls)
		})
	}
}

func TestEquivalentGeneratedExpressions(t *testing.T) {
	table := func(expr string) string {
		return "CREATE TABLE T (Id INT64 NOT NULL, N INT64 AS (" + expr + ") STORED) PRIMARY KEY(Id)"
	}
	for _, pair := range [][2]string{
		{"ABS(Id)", "abs(Id)"}, {"ABS(Id)", "ABS(id)"}, {"Id + 1", "((id + 1))"},
		{"ABS(Id + 1)", "abs(((id + 1)))"}, {"Id * (Id + 1)", "(id) * ((id + 1))"},
	} {
		current := table(pair[0])
		desired := strings.Replace(table(pair[1]), "Id INT64 NOT NULL,", "Id INT64 NOT NULL, Extra INT64,", 1)
		ddls, err := GenerateIdempotentDDLs(desired, current, GeneratorConfig{})
		require.NoError(t, err)
		require.Equal(t, []string{"ALTER TABLE T ADD COLUMN Extra INT64"}, ddls)
	}
	for _, pair := range [][2]string{
		{"Id * (Id + 1)", "Id * Id + 1"}, {"Id - (Id - 1)", "(Id - Id) - 1"},
		{"ABS(Id)", "SIGN(Id)"}, {"LENGTH('A') + Id", "LENGTH('a') + Id"},
	} {
		ddls, err := GenerateIdempotentDDLs(table(pair[1]), table(pair[0]), GeneratorConfig{})
		require.ErrorContains(t, err, "unsupported generation or visibility change")
		require.Empty(t, ddls)
	}
	current := "CREATE TABLE T (Id INT64 NOT NULL, J JSON, N JSON AS (J.Foo) STORED) PRIMARY KEY(Id)"
	ddls, err := GenerateIdempotentDDLs(strings.Replace(current, "J.Foo", "J.foo", 1), current, GeneratorConfig{})
	require.ErrorContains(t, err, "unsupported generation or visibility change")
	require.Empty(t, ddls)
	ddls, err = GenerateIdempotentDDLs(strings.Replace(current, " STORED", "", 1), current, GeneratorConfig{})
	require.ErrorContains(t, err, "unsupported generation or visibility change")
	require.Empty(t, ddls)
}
