package spannerdef

import (
	"fmt"
	"github.com/cloudspannerecosystem/memefish/ast"
	"reflect"
	"slices"
)

func canonicalKeySQL(key *ast.IndexKey) string {
	var name string
	if key.Name != nil {
		name = key.Name.SQL()
	} else {
		name = "(" + key.Expr.SQL() + ")"
	}
	if key.Dir == ast.DirectionDesc {
		return name + " DESC"
	}
	// Explicit ASC and an omitted direction have identical semantics.
	return name
}

func validateKeyChanges(current, desired *Schema) error {
	for name, next := range desired.Tables {
		if prev, ok := current.Tables[name]; ok && (!slices.Equal(prev.PrimaryKey, next.PrimaryKey) || (len(prev.PrimaryKey) == 0 && prev.PrimaryKeyExplicit != next.PrimaryKeyExplicit)) {
			return fmt.Errorf("unsupported primary key change for table %s", name)
		}
	}
	for name, next := range desired.Indexes {
		if prev, ok := current.Indexes[name]; ok &&
			(prev.TableName != next.TableName || prev.Unique != next.Unique || prev.NullFiltered != next.NullFiltered || !sameIndexKeys(prev, next) || !sameStoredColumns(prev.Storing, next.Storing)) {
			return fmt.Errorf("unsupported definition change for index %s; migrate the index explicitly", name)
		}
	}
	return nil
}

func sameStoredColumns(a, b []string) bool {
	a = slices.Clone(a)
	b = slices.Clone(b)
	slices.Sort(a)
	slices.Sort(b)
	return slices.Equal(a, b)
}

// Spanner expands an omitted primary key into this hidden identity column.
// Only recognize that exact shape; an explicit empty key is a singleton table.
func normalizeImplicitPrimaryKeys(current, desired *Schema) {
	for name, next := range desired.Tables {
		prev := current.Tables[name]
		if prev == nil || next.PrimaryKeyExplicit || len(next.PrimaryKey) != 0 || next.Columns["rowid"] != nil || !slices.Equal(prev.PrimaryKey, []string{"rowid"}) {
			continue
		}
		col := prev.Columns["rowid"]
		if col == nil || col.Type != "INT64" || !col.NotNull || !col.Hidden || col.Generation != "GENERATED BY DEFAULT AS IDENTITY (BIT_REVERSED_POSITIVE)" || col.Default != "" || col.OnUpdate != "" || col.Options != "" {
			continue
		}
		copyColumn := *col
		next.Columns["rowid"] = &copyColumn
		next.PrimaryKey = []string{"rowid"}
		next.PrimaryKeyExplicit = true
	}
}

func sameIndexKeys(a, b *Index) bool {
	if a.keys == nil || b.keys == nil {
		return slices.Equal(a.Columns, b.Columns)
	}
	if len(a.keys) != len(b.keys) {
		return false
	}
	for i, left := range a.keys {
		right := b.keys[i]
		if (left.Dir == ast.DirectionDesc) != (right.Dir == ast.DirectionDesc) {
			return false
		}
		if left.Name != nil || right.Name != nil {
			if left.Name == nil || right.Name == nil || left.Name.SQL() != right.Name.SQL() {
				return false
			}
		} else if !equalGenerationAST(reflect.ValueOf(left.Expr), reflect.ValueOf(right.Expr)) {
			return false
		}
	}
	return true
}
