package spannerdef

import (
	"github.com/stretchr/testify/require"
	"testing"
)

func TestPrimaryKeyForms(t *testing.T) {
	for _, ddl := range []string{"CREATE TABLE T (N INT64) PRIMARY KEY ()", "CREATE TABLE T (N INT64, PRIMARY KEY ())"} {
		ddls, err := GenerateIdempotentDDLs(ddl, "", GeneratorConfig{})
		require.NoError(t, err)
		require.Contains(t, ddls[0], "PRIMARY KEY ()")
		_, err = GenerateIdempotentDDLs("CREATE TABLE T (N INT64)", ddl, GeneratorConfig{})
		require.ErrorContains(t, err, "primary key change")
	}
	omitted := "CREATE TABLE T (N INT64)"
	expanded := "CREATE TABLE T (N INT64, rowid INT64 NOT NULL GENERATED BY DEFAULT AS IDENTITY (BIT_REVERSED_POSITIVE) HIDDEN) PRIMARY KEY (rowid)"
	ddls, err := GenerateIdempotentDDLs(omitted, expanded, GeneratorConfig{})
	require.NoError(t, err)
	require.Empty(t, ddls)
	ddls, err = GenerateIdempotentDDLs("CREATE TABLE T (N INT64, S STRING(MAX))", expanded, GeneratorConfig{})
	require.NoError(t, err)
	require.Equal(t, []string{"ALTER TABLE T ADD COLUMN S STRING(MAX)"}, ddls)
	_, err = GenerateIdempotentDDLs(omitted, "CREATE TABLE T (N INT64, rowid INT64 NOT NULL) PRIMARY KEY (rowid)", GeneratorConfig{})
	require.ErrorContains(t, err, "primary key change")
	_, err = GenerateIdempotentDDLs(omitted+" PRIMARY KEY ()", expanded, GeneratorConfig{})
	require.ErrorContains(t, err, "primary key change")
}
func TestExpressionIndex(t *testing.T) {
	ddl := `CREATE TABLE T (Id INT64 NOT NULL, Name STRING(MAX)) PRIMARY KEY (Id); CREATE INDEX IX ON T((LOWER(Name)) DESC)`
	ddls, err := GenerateIdempotentDDLs(ddl, "", GeneratorConfig{})
	require.NoError(t, err)
	require.Contains(t, ddls[1], "((LOWER(Name)) DESC)")
	ddls, err = GenerateIdempotentDDLs(ddl, ddl, GeneratorConfig{})
	require.NoError(t, err)
	require.Empty(t, ddls)
	_, err = GenerateIdempotentDDLs(ddl, `CREATE TABLE T (Id INT64 NOT NULL, Name STRING(MAX)) PRIMARY KEY (Id); CREATE INDEX IX ON T(Name)`, GeneratorConfig{})
	require.ErrorContains(t, err, "definition change")
}

func TestEquivalentExpressionIndex(t *testing.T) {
	current := `CREATE TABLE T(Id INT64, Name STRING(MAX)) PRIMARY KEY(Id); CREATE INDEX IX ON T((LOWER(Name)))`
	desired := `CREATE TABLE T(Id INT64, Name STRING(MAX), N INT64) PRIMARY KEY(Id); CREATE INDEX IX ON T((lower((Name))) ASC)`
	ddls, err := GenerateIdempotentDDLs(desired, current, GeneratorConfig{})
	require.NoError(t, err)
	require.Equal(t, []string{"ALTER TABLE T ADD COLUMN N INT64"}, ddls)
}
