name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        check-latest: true

    - name: Run tests
      run: |
        # Run only unit tests (no integration tests that require Spanner emulator)
        go test ./cmd/spannerdef -v
        go test . -v -run "TestParseDDLs|TestGenerateDDLs"

    - name: Set up environment variables
      run: |
        echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        echo "BUILD_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_ENV

    - name: Build binaries
      run: |
        mkdir -p dist
        
        # macOS ARM64
        GOOS=darwin GOARCH=arm64 go build \
          -ldflags="-s -w -X main.version=${{ env.VERSION }} -X main.buildDate=${{ env.BUILD_DATE }}" \
          -o dist/spannerdef-${{ env.VERSION }}-darwin-arm64 \
          ./cmd/spannerdef
        
        # macOS AMD64
        GOOS=darwin GOARCH=amd64 go build \
          -ldflags="-s -w -X main.version=${{ env.VERSION }} -X main.buildDate=${{ env.BUILD_DATE }}" \
          -o dist/spannerdef-${{ env.VERSION }}-darwin-amd64 \
          ./cmd/spannerdef
        
        # Linux ARM64
        GOOS=linux GOARCH=arm64 go build \
          -ldflags="-s -w -X main.version=${{ env.VERSION }} -X main.buildDate=${{ env.BUILD_DATE }}" \
          -o dist/spannerdef-${{ env.VERSION }}-linux-arm64 \
          ./cmd/spannerdef
        
        # Linux AMD64
        GOOS=linux GOARCH=amd64 go build \
          -ldflags="-s -w -X main.version=${{ env.VERSION }} -X main.buildDate=${{ env.BUILD_DATE }}" \
          -o dist/spannerdef-${{ env.VERSION }}-linux-amd64 \
          ./cmd/spannerdef

    - name: Generate checksums
      run: |
        cd dist
        sha256sum * > checksums.txt

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        draft: false
        prerelease: false
        generate_release_notes: true
        files: |
          dist/*
        body: |
          ## What's New
          
          Release ${{ env.VERSION }} of spannerdef
          
          ### Download
          
          Choose the binary for your platform:
          
          **macOS:**
          - [spannerdef-${{ env.VERSION }}-darwin-arm64](https://github.com/${{ github.repository }}/releases/download/${{ env.VERSION }}/spannerdef-${{ env.VERSION }}-darwin-arm64) (Apple Silicon)
          - [spannerdef-${{ env.VERSION }}-darwin-amd64](https://github.com/${{ github.repository }}/releases/download/${{ env.VERSION }}/spannerdef-${{ env.VERSION }}-darwin-amd64) (Intel)
          
          **Linux:**
          - [spannerdef-${{ env.VERSION }}-linux-arm64](https://github.com/${{ github.repository }}/releases/download/${{ env.VERSION }}/spannerdef-${{ env.VERSION }}-linux-arm64) (ARM64)
          - [spannerdef-${{ env.VERSION }}-linux-amd64](https://github.com/${{ github.repository }}/releases/download/${{ env.VERSION }}/spannerdef-${{ env.VERSION }}-linux-amd64) (AMD64)
          
          ### Verification
          
          You can verify the integrity of downloaded files using the checksums:
          ```bash
          sha256sum -c checksums.txt
          ```
          
          ### Installation
          
          1. Download the appropriate binary for your platform
          2. Make it executable: `chmod +x spannerdef-*`
          3. Move to your PATH: `sudo mv spannerdef-* /usr/local/bin/spannerdef`
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}